# Generated by Django 2.1.7 on 2020-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pla_auc',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=50),
        ),
    ]
