# Generated by Django 2.1.7 on 2020-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_pla_auc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pla_auc',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='', max_length=50),
        ),
    ]
