# Generated by Django 2.1.7 on 2020-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pla_auc',
            field=models.CharField(choices=[('no', 'no'), ('yes', 'yes')], default='no', max_length=50),
        ),
    ]
