# Generated by Django 2.1.7 on 2020-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200402_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zz',
            field=models.CharField(choices=[('do', 'do'), ('notdo', 'notdo')], default='', max_length=256),
        ),
    ]
