# Generated by Django 2.1.7 on 2020-04-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_zz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='zz',
        ),
    ]
