# Generated by Django 2.1.7 on 2020-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200416_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='product_category',
            field=models.CharField(choices=[('electronic', 'electronic'), ('propertie', 'propertie'), ('art', 'art')], default='electronic', max_length=256),
        ),
    ]
