# Generated by Django 2.1.7 on 2020-03-31 13:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_country', models.CharField(choices=[('India', 'India'), ('England', 'England'), ('Australia', 'Australia'), ('Newzealand', 'Newzealand')], default='', max_length=50)),
                ('player_role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('AllRounder', 'AllRounder')], default='', max_length=50)),
                ('base_price', models.IntegerField(default='')),
                ('raising_price', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sell_price', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('bidding', 'bidding'), ('unsold', 'unsold'), ('sold', 'sold')], default='', max_length=50)),
                ('sell_teamName', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('hour', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('minite', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('second', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
