# Generated by Django 2.1.7 on 2020-04-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='player_pics'),
        ),
    ]
